### ISSUE TITLE
Suggestion:  Condense your components and drawing boards

### ISSUE THREAD

**Issue by delebash** [LingFengSBH/InteractiveWorld#3]
Instead of having separate components and drawing boards  for snow, mud, and so on just have 1 for feet and 1 for objects and a BP Manager component.    Have right and left for feet where you just enable or disable trails or footprint stamp or both regardless of the type of terrain.  You can enable/disable based on terrain type via physical material.  Here is an example of a deformation system like this.  https://www.youtube.com/watch?v=FW4twCpIL6w.  You can see in the Material you just enable/disable for each landscape layer type.  

![UnrealEditor_IOzbYItOyf](https://user-images.githubusercontent.com/2220160/219393051-8d70fce9-a38a-4116-b3c0-e3712d023a71.png)

You have really nice system, I look forward to seeing what you continue to do with it.

**Comment by LingFengSBH** [comment]
Hi, I have tried many different ways to organize this system.
And I want to create a system which is easy to expand, this is what I care about most. 
The reason why I didn't compose these brushes into one material or component is that I want to make it easy to add more simulation drawing boards in the future.
For example, an interactive fog, and fluid simulation with N-S equation.
You have a good idea, in fact, I'm using similar way with yours in my other projects. Your solution is more effective, but I want to make this plugin easier to expand.

**Comment by LingFengSBH** [comment]
And you can also create a new child class of WorldInteractBrush, and disable UseDrawOnlyDrawingBoardClassList.
So that this brush can draw on all type of drawing boards.

**Comment by delebash** [comment]
Cool
