### ISSUE TITLE
How do you get more definition for the footprint stamp.

### ISSUE THREAD

**Issue by delebash** [LingFengSBH/InteractiveWorld#4]
Here is a picture where  I used a footprint texture on the BP_Wheel.  You can see the shape of the toes.  On the character I am using the same texture but I do not see the shape of the toes.  Is there a  way to get increase the definition so I can see the toes for my footprint?

![UnrealEditor_WoSr8DhkkV](https://user-images.githubusercontent.com/2220160/219394660-5c0a461f-bb66-4476-9b74-01472f2a5203.png)

![UnrealEditor_4Xfh8UMaOH](https://user-images.githubusercontent.com/2220160/219394688-bb06c645-e818-4a66-8fd1-a677bb442917.png)

**Comment by LingFengSBH** [comment]
You can run "EUW_DrawingBoardSettings" and find mud settings.
![image](https://user-images.githubusercontent.com/75574618/219396334-68858365-e509-4f5a-92fa-5b7dc427f42a.png)
and reduce World Size or enlarge RT Size

**Comment by delebash** [comment]
Thanks!
