### ISSUE TITLE
Texture From Mesh Creator

### ISSUE THREAD

**Issue by delebash** [LingFengSBH/InteractiveWorld#5]
Hi,  I made a little tool I wanted to share with you.  It creates alpha stamps from a characters shoe.   Interactive World has a nice footprint stamp system and this way we can quickly create alpha textures for Skeletal and Static meshes to be used in your system.  Take look.  Thanks for making Interactive World!

https://youtu.be/HL54vKHMjtk

**Comment by LingFengSBH** [comment]
Thanks, you have a lot of good ideas. It really inspired me.

**Comment by delebash** [comment]
Awesome!
