### ISSUE TITLE
How do I enable foot prints in the snow and disable trails

### ISSUE THREAD

**Issue by delebash** [LingFengSBH/InteractiveWorld#6]
Is there a way to enable/disable trails and footprints.  For example if I just want footprints in the snow how do I do this.  Also if I want footprints and trails in the mud how do I do this?  Thanks.

**Comment by LingFengSBH** [comment]
You can find a variable named "Draw Only DraingBoard Class List" in InteractBrush.

**Comment by delebash** [comment]
ty
