### ISSUE TITLE
Do you have an example for using this with a landscape material

### ISSUE THREAD

**Issue by delebash** [LingFengSBH/InteractiveWorld#7]
Can you include an example of setting this up using a landscape material.  It looked like in your docs you originally had it setup using a landscape material. 

![chrome_9lrBKLDS9W](https://user-images.githubusercontent.com/2220160/222946836-8659825b-0a1f-4688-aeae-03283ac930d2.png)

 You mentioned using VHFM but the demo isn't using a landscape. So if I have an auto material with mud, snow, grass layers how do I hookup interact.  In the current example the snow is above the ground and in your docs you say 

UV:UV of Render Target,if you want to sample Output RT of Drawing Board,you should use this UV,so that it will be mapped on the ground

but I don't really understand how I would hook this up in my landscape snow material.

Thanks!

**Comment by VvK0123** [comment]
Really need tutor with landscape! currently snow material not working with lanscape!

**Comment by delebash** [comment]
I see the other demo https://github.com/LingFengSBH/InteractiveWorldDemo has an example with landscape, thanks :)
